# -*- coding: utf-8 -*-
"""churn_modeling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bO1kvqctn_duvv3VPCq4pI0X0pk36Xq8
"""

import pandas as pd

import numpy as np
import matplotlib.pyplot as plt

df=pd.read_csv('ch.csv')

x=df.iloc[:,3:13]

x

y=df.iloc[:,13]

y

Geography=pd.get_dummies(x['Geography'],drop_first=True)

Geography

gender=pd.get_dummies(x['Gender'],drop_first=True)

gender

x=pd.concat([x,Geography,Gender],axis=1)

x

x=x.drop(['Gender','Geography'],axis=1)

x

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

from sklearn.preprocessing import StandardScaler

sc=StandardScaler()

x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

import keras

from keras.models import Sequential

from keras.layers import Dense

from keras.layers import Dropout

classifer=Sequential()

classifer.add(Dense(units=10,kernel_initializer='he_uniform',activation='relu',input_dim=11))

classifer.add(Dense(units=10,kernel_initializer='he_uniform',activation='relu'))

classifer.add(Dense(units=8,kernel_initializer='he_uniform',activation='relu'))

classifer.add(Dense(units=1,kernel_initializer='glorot_normal',activation='sigmoid'))

classifer.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

model_history=classifer.fit(x_train,y_train,validation_split=0.33,batch_size=10,epochs=100)

y_predit=classifer.predict(x_test)

y_predit=(y_predit>0.5)

from sklearn.metrics import confusion_matrix

cm=confusion_matrix(y_predit,y_test)

from sklearn.metrics import accuracy_score

score=accuracy_score(y_predit,y_test)

score

